spring:
  application:
    name: non-working-days

logging:
  level:
    ru.ru.darin.coordinates: info
    org:
      springframework: ${LOG:info}
  file:
    name: logs/log

non-working-days:
  openapi:
    dev-url: http://localhost:8080